data<-read.csv("household_power_consumption.txt",sep=";",stringsAsFactors=F)
data$Date<-as.Date(data$Date,format="%d/%m/%Y")
subData<-data[data$Date>=as.Date("2007-02-01") & data$Date <= as.Date("2007-02-02"),]
rm(data)
subData$Sub_metering_1<-as.numeric(subData$Sub_metering_1)
subData$Sub_metering_2<-as.numeric(subData$Sub_metering_2)
subData$Sub_metering_3<-as.numeric(subData$Sub_metering_3)
indexs=tapply(seq(1:nrow(subData)),weekdays(subData$Date,abbreviate=T),min)
lab=sapply(indexs,function(x)weekdays(subData[x,1],abbreviate=T))
indexs=c(indexs,nrow(subData)+1)
lab=c(lab,weekdays(subData[nrow(subData),1]+1,abbreviate=T))
png("plot3.png",width=480,height=480)
with(subData,plot(subData$Sub_metering_1,type="l",lwd=1,xaxt="n",ylab="Energy sub metering",xlab="",col="black"))
with(subData,lines(subData$Sub_metering_2,col="red"))
with(subData,lines(subData$Sub_metering_3,col="blue"))
legend("topright",lty=c(1,1),col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
axis(1,indexs,labels=lab)
dev.off()